# Generated by Django 6.0 on 2025-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_feedback',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
