# Generated by Django 6.0 on 2025-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_client_feedback_name_client_feedback_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Suscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
